FROM ubuntu:20.04 as base

RUN apt -y update \
  && apt -y install zsh \ 
  && apt -y install git \
  && apt -y install curl wget
RUN DEBIAN_FRONTEND=noninteractive TZ=Australia/Melbourne apt -y install libffi-dev \ 
                   # libbz2-dev \
                   libreadline-dev \
                   libssl-dev \
                   libsqlite3-dev \
                   liblzma-dev \
                   build-essential \
                   zlib1g-dev \
                   llvm \ 
                   make \ 
                   libncursesw5-dev \ 
                   xz-utils \ 
                   tk-dev \ 
                   libxml2-dev \ 
                   libxmlsec1-dev \
                   neovim \
                   icu-devtools \ 
                   libexpat1-dev \
                   libicu-dev \
                   libicu66 \
                   libxml2 \
                   libxml2-dev \
                   tzdata \
                   python3-venv 
 
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
RUN echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc

# install asdf 
RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
RUN echo '. "$HOME/.asdf/asdf.sh"' >>~/.zshrc

# install python
RUN ~/.asdf/bin/asdf plugin add python
RUN ~/.asdf/bin/asdf install python 3.11.0
RUN ~/.asdf/bin/asdf global python 3.11.0
RUN ~/.asdf/bin/asdf local python 3.11.0


# Install mojo
RUN curl -y 1  https://get.modular.com | sh - && modular auth mut_4e91d2c84f1b43acb4996bdaa8662b95
RUN modular install mojo

FROM base as dev
COPY .p10k.zsh /root/.p10k.zsh
RUN echo 'if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then \n source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" \n fi' >> ~/.zshrc
RUN echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc
RUN echo 'export MODULAR_HOME="/root/.modular"' >> ~/.zshrc
RUN echo 'export PATH="/root/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.zshrc
WORKDIR /root
CMD [ "/bin/zsh" ]
